name: Github Action 실행

on:
    push:
        branches:
            - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest


    steps:
        - name: hello world 찍기
            run: echo "hello world"


                - name: 여러명령어 실행
                    run: |
                    echo "hello world!!!"
                    echo "good !!!!"
